// Code generated by protoc-gen-go. DO NOT EDIT.
// source: downloader.proto

package downloader

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmployeeDownloadFileRequest struct {
	AdminID              string   `protobuf:"bytes,1,opt,name=adminID,proto3" json:"adminID,omitempty"`
	TotalEmployeeCount   int64    `protobuf:"varint,2,opt,name=total_employee_count,json=totalEmployeeCount,proto3" json:"total_employee_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeDownloadFileRequest) Reset()         { *m = EmployeeDownloadFileRequest{} }
func (m *EmployeeDownloadFileRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeeDownloadFileRequest) ProtoMessage()    {}
func (*EmployeeDownloadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a99ec95c7ab1ff1, []int{0}
}

func (m *EmployeeDownloadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeDownloadFileRequest.Unmarshal(m, b)
}
func (m *EmployeeDownloadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeDownloadFileRequest.Marshal(b, m, deterministic)
}
func (m *EmployeeDownloadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeDownloadFileRequest.Merge(m, src)
}
func (m *EmployeeDownloadFileRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeeDownloadFileRequest.Size(m)
}
func (m *EmployeeDownloadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeDownloadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeDownloadFileRequest proto.InternalMessageInfo

func (m *EmployeeDownloadFileRequest) GetAdminID() string {
	if m != nil {
		return m.AdminID
	}
	return ""
}

func (m *EmployeeDownloadFileRequest) GetTotalEmployeeCount() int64 {
	if m != nil {
		return m.TotalEmployeeCount
	}
	return 0
}

type EmployeeDownloadFileResponse struct {
	EmployeeDetails      []*EmployeeDownloadFileResponseEmployeeData `protobuf:"bytes,1,rep,name=employee_details,json=employeeDetails,proto3" json:"employee_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *EmployeeDownloadFileResponse) Reset()         { *m = EmployeeDownloadFileResponse{} }
func (m *EmployeeDownloadFileResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeeDownloadFileResponse) ProtoMessage()    {}
func (*EmployeeDownloadFileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a99ec95c7ab1ff1, []int{1}
}

func (m *EmployeeDownloadFileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeDownloadFileResponse.Unmarshal(m, b)
}
func (m *EmployeeDownloadFileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeDownloadFileResponse.Marshal(b, m, deterministic)
}
func (m *EmployeeDownloadFileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeDownloadFileResponse.Merge(m, src)
}
func (m *EmployeeDownloadFileResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeeDownloadFileResponse.Size(m)
}
func (m *EmployeeDownloadFileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeDownloadFileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeDownloadFileResponse proto.InternalMessageInfo

func (m *EmployeeDownloadFileResponse) GetEmployeeDetails() []*EmployeeDownloadFileResponseEmployeeData {
	if m != nil {
		return m.EmployeeDetails
	}
	return nil
}

type EmployeeDownloadFileResponseEmployeeData struct {
	EmployeeData         []string `protobuf:"bytes,1,rep,name=employee_data,json=employeeData,proto3" json:"employee_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeDownloadFileResponseEmployeeData) Reset() {
	*m = EmployeeDownloadFileResponseEmployeeData{}
}
func (m *EmployeeDownloadFileResponseEmployeeData) String() string { return proto.CompactTextString(m) }
func (*EmployeeDownloadFileResponseEmployeeData) ProtoMessage()    {}
func (*EmployeeDownloadFileResponseEmployeeData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a99ec95c7ab1ff1, []int{1, 0}
}

func (m *EmployeeDownloadFileResponseEmployeeData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeDownloadFileResponseEmployeeData.Unmarshal(m, b)
}
func (m *EmployeeDownloadFileResponseEmployeeData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeDownloadFileResponseEmployeeData.Marshal(b, m, deterministic)
}
func (m *EmployeeDownloadFileResponseEmployeeData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeDownloadFileResponseEmployeeData.Merge(m, src)
}
func (m *EmployeeDownloadFileResponseEmployeeData) XXX_Size() int {
	return xxx_messageInfo_EmployeeDownloadFileResponseEmployeeData.Size(m)
}
func (m *EmployeeDownloadFileResponseEmployeeData) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeDownloadFileResponseEmployeeData.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeDownloadFileResponseEmployeeData proto.InternalMessageInfo

func (m *EmployeeDownloadFileResponseEmployeeData) GetEmployeeData() []string {
	if m != nil {
		return m.EmployeeData
	}
	return nil
}

func init() {
	proto.RegisterType((*EmployeeDownloadFileRequest)(nil), "downloader.EmployeeDownloadFileRequest")
	proto.RegisterType((*EmployeeDownloadFileResponse)(nil), "downloader.EmployeeDownloadFileResponse")
	proto.RegisterType((*EmployeeDownloadFileResponseEmployeeData)(nil), "downloader.EmployeeDownloadFileResponse.employee_data")
}

func init() { proto.RegisterFile("downloader.proto", fileDescriptor_6a99ec95c7ab1ff1) }

var fileDescriptor_6a99ec95c7ab1ff1 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xc9, 0x2f, 0xcf,
	0xcb, 0xc9, 0x4f, 0x4c, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0x65, 0x72, 0x49, 0xbb, 0xe6, 0x16, 0xe4, 0xe4, 0x57, 0xa6, 0xa6, 0xba, 0x40, 0x45, 0xdd,
	0x32, 0x73, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x24, 0xb8, 0xd8, 0x13, 0x53,
	0x72, 0x33, 0xf3, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x60, 0x5c, 0x21, 0x03,
	0x2e, 0x91, 0x92, 0xfc, 0x92, 0xc4, 0x9c, 0xf8, 0x54, 0xa8, 0xf6, 0xf8, 0xe4, 0xfc, 0xd2, 0xbc,
	0x12, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x21, 0xb0, 0x1c, 0xcc, 0x64, 0x67, 0x90, 0x8c,
	0xd2, 0x76, 0x46, 0x2e, 0x19, 0xec, 0x76, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x25, 0x72,
	0x09, 0xc0, 0x0d, 0x4b, 0x49, 0x2d, 0x49, 0xcc, 0xcc, 0x29, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0,
	0x36, 0x32, 0xd3, 0x43, 0xf2, 0x04, 0x3e, 0x33, 0xf4, 0x10, 0x06, 0x24, 0x96, 0x24, 0x06, 0xf1,
	0xc3, 0xb8, 0x2e, 0x10, 0xe3, 0xa4, 0x4c, 0xb8, 0x78, 0x51, 0x54, 0x08, 0x29, 0xa3, 0x09, 0x80,
	0x2d, 0xe4, 0x0c, 0xe2, 0x81, 0x6b, 0x4c, 0x2c, 0x49, 0x34, 0x6a, 0x62, 0xe4, 0xe2, 0x87, 0xd9,
	0x16, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x94, 0xcf, 0x25, 0x01, 0x13, 0x82, 0x39, 0x08,
	0xe4, 0x10, 0x90, 0x7a, 0x21, 0x75, 0xc2, 0xce, 0x05, 0x07, 0xaf, 0x94, 0x06, 0xb1, 0xfe, 0x52,
	0x62, 0x48, 0x62, 0x03, 0x47, 0x9e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xff, 0x0b, 0x88, 0x72,
	0xd0, 0x01, 0x00, 0x00,
}
